import type { XDashboardDiscoverySkill } from "./xskills";

export const XCALENDAR_SKILL: XDashboardDiscoverySkill = {
  _id: "xcalendar",
  _title: "XCalendar",
  _version: "1.0.0",
  _active: true,
  _type: "view-skill",
  _category: "collection-presentation",
  _purpose: "date-oriented calendar/schedule presentation of records",
  _aliases: [
    "calendar",
    "schedule",
    "planner",
    "month view",
    "agenda",
    "date view",
    "date grid",
    "event calendar",
    "events calendar",
    "calendar grid",
  ],
  _capabilities: [
    "date-layout",
    "scheduled-records",
    "schedule-view",
    "calendar-view",
  ],
  _bindings: {
    _collection: ["_data_source", "_items"],
    _date: ["_date_field"],
    _start_date: ["_date_field"],
    _end_date: ["_end_date_field"],
    _view: ["_view"],
    _view_state: ["_view", "_month", "_week_start"],
    _item: [
      "_item._title",
      "_item._subtitle",
      "_item._description",
      "_item._meta",
      "_item._icon",
      "_item._image",
      "_item._image_alt",
      "_item._badge",
      "_item._actions",
    ],
    _actions: ["_item._actions", "_actions"],
    _events: ["xcalendar:item-select", "xcalendar:month-change", "_on_select"],
  },
  _usage: [
    "Use when supplied records should be placed on a month calendar by date/time fields.",
    "Use _date_field for the required start date/time path.",
    "Use _end_date_field when records span multiple days.",
    "Use _view:'month' for the calendar mode supported by this component.",
    "Use _month to control the visible month and the built-in previous, next, and today controls for local calendar navigation.",
    "Prefer table for dense structured data.",
    "Prefer xgallery for visual cards.",
    "Prefer xlist for compact scanning.",
    "Prefer xkanban for workflow/grouping.",
    "Prefer xtimeline for chronological history.",
    "Prefer xcalendar for records organized by calendar date.",
    "The component only presents supplied records; it does not query, filter, or persist calendar data.",
  ],
  _use_cases: [
    "appointments",
    "reminders",
    "bookings",
    "tasks with dates",
    "maintenance",
    "shifts",
    "deliveries",
    "scheduled events",
  ],
  _presentation: {
    _kind: "collection",
    _mode: "calendar",
    _alternatives: [
      "table",
      "xgallery",
      "xlist",
      "xkanban",
      "xtimeline",
      "xcalendar",
    ],
    _prefer_when: [
      "records are organized by calendar date",
      "records need placement on dates in a month grid",
      "multiple records per day should be scanned together",
      "records may span from a start date to an optional end date",
    ],
  },
  _requires: ["xuiobject", "xdata", "badge", "empty"],
  _match: {
    _keywords: [
      "calendar",
      "schedule",
      "planner",
      "month",
      "month view",
      "agenda",
      "date view",
      "date grid",
      "calendar grid",
      "event calendar",
      "events calendar",
      "appointments",
      "reminders",
      "bookings",
      "tasks with dates",
      "maintenance",
      "shifts",
      "deliveries",
      "scheduled events",
      "start at",
      "end at",
      "date",
      "time",
    ],
    _priority: 89,
  },

  _description:
    "Generic data-bound calendar component that renders supplied records in a responsive month grid with mapped title, subtitle, description, metadata, optional icon/image, badge/status, per-item actions, selection, and previous/next/today navigation.",

  _fields: {
    _items:
      "Static item array or XData key string. Use _data_source for XData-bound calendar records.",
    _data_source:
      "Optional XData key used to hydrate and update calendar records, for example event.records.",
    _date_field:
      "Required record field or $row path used as the start date/time, for example start_at or $row.schedule.start.",
    _end_date_field:
      "Optional record field or $row path used as the end date/time. Multi-day records are placed on each visible day in the inclusive date range.",
    _view: "Calendar view mode. Currently supports month.",
    _month:
      "Visible month as YYYY-MM or a date string. Defaults to the current month.",
    _week_start: "Week start: sun or mon. Defaults to sun.",
    _item:
      "Item mapping object. Supports _title, _subtitle, _description, _meta, _icon, _image, _image_alt, _badge, and _actions. String values may use $row, $row.field, and $row_index.",
    _actions:
      "Optional per-item action child objects used when _item._actions is not set. Action templates receive _row, _row_index, and _context.",
    _row_key: "Optional row field used for stable item and action ids.",
    _selectable: "Enable item click/keyboard selection.",
    _selected_key: "Optional selected row key.",
    _empty_text:
      "Text shown when the visible month has no valid record placements.",
    _empty:
      "Optional empty-state XUI object. Defaults to an empty object using _empty_text.",
    _on_data:
      "Optional data handler. For persisted/generated views, use Nano-Commands/data-only, not functions.",
    class: "Optional CSS classes. xcalendar is applied automatically.",
  },

  _core_rules: [
    "Use xcalendar to present supplied date-based records in a month grid.",
    "Keep the component generic; do not add entity-specific rendering, fetching, querying, filtering, or persistence logic.",
    "Use _data_source when records should come from XData.",
    "Use _items for static records or for an XData key string.",
    "Use _date_field for each record's start date/time path.",
    "Use _end_date_field only when records may span multiple days.",
    "Use _view:'month'; do not infer unsupported agenda/week/day rendering.",
    "Use _month to set or update the visible month.",
    "Use _item to map generic record fields; do not add domain-specific rendering logic.",
    "Supported item mappings include _title, _subtitle, _description, _meta, _icon, _image, _image_alt, _badge, and _actions.",
    "Use _item._actions or _actions for per-item buttons, links, or menu controls.",
    "Per-item action templates may reference $row, $row.field, and $row_index.",
    "Item clicks emit xcalendar:item-select and may invoke runtime _on_select.",
    "Calendar navigation emits xcalendar:month-change.",
    "For persisted/generated views, handlers must be Nano-Commands/data-only.",
  ],

  _canonical_examples: [
    {
      _type: "xcalendar",
      _id: "event-calendar",
      _data_source: "event.records",
      _date_field: "start_at",
      _end_date_field: "end_at",
      _view: "month",
      _month: "2026-08",
      _row_key: "id",
      _item: {
        _title: "$row.title",
        _subtitle: "$row.location",
        _description: "$row.notes",
        _badge: "$row.status",
        _actions: [
          {
            _type: "button",
            _text: "Open",
          },
        ],
      },
      _empty_text: "No records",
    },
  ],
};
